# Use root/example as user/password credentials
version: '3.1'

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
    

  mysql_server:
    image: mysql:latest
    network_mode: "host"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=povio
      - MYSQL_USER=root
      - MYSQL_PASSWORD=adminadmin
      - MYSQL_ROOT_PASSWORD=adminadmin