version: '2.1'
services:

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/data/
    networks:
      - 'local'

networks:
  local:
    driver: 'bridge'

volumes:
  postgres-data:
    driver: local
